import express from "express";
import path from "path";
import dotenv from "dotenv";
import fs from "fs";
import JSZip from "jszip";
import { GoogleGenAI, Type, FunctionDeclaration } from "@google/genai";
import { createServer as createViteServer } from "vite";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json({ limit: "50mb" }));

// Define a function declaration for dependency retrieval and code correction
const requestDependencyDownloadDeclaration: FunctionDeclaration = {
  name: "requestDependencyDownload",
  description: "Solicita a busca e o download de uma DLL, código ou arquivo ausente no projeto de jogo.",
  parameters: {
    type: Type.OBJECT,
    properties: {
      dependencyName: {
        type: Type.STRING,
        description: "Nome exato da DLL, arquivo, biblioteca ou script ausente (ex: Newtonsoft.Json.dll, PlayerController.cs).",
      },
      reason: {
        type: Type.STRING,
        description: "Explicação em português de por que essa dependência é necessária e o que está quebrado sem ela.",
      },
      fileType: {
        type: Type.STRING,
        description: "Tipo de arquivo: 'dll', 'cs', 'cpp', 'js', 'unitypackage', 'json', etc.",
      },
      recommendedSource: {
        type: Type.STRING,
        description: "Link oficial recomendado ou origem para obter o arquivo (ex: NuGet, GitHub, dll-files, etc).",
      },
      autoGeneratedContent: {
        type: Type.STRING,
        description: "Se for um arquivo de código ou stub, o código-fonte completo ou conteúdo gerado pela IA para corrigir o arquivo.",
      }
    },
    required: ["dependencyName", "reason", "fileType"]
  }
};

// Helper to convert Gemini payload to OpenAI / Groq / OpenRouter Messages format
function convertToOpenAIMessages(systemInstruction: string, formattedContents: any[]) {
  const messages: any[] = [];
  if (systemInstruction) {
    messages.push({ role: "system", content: systemInstruction });
  }

  for (const item of formattedContents) {
    const role = item.role === "model" ? "assistant" : "user";
    const contentParts: any[] = [];

    if (Array.isArray(item.parts)) {
      for (const p of item.parts) {
        if (p.text) {
          contentParts.push({ type: "text", text: p.text });
        } else if (p.inlineData) {
          contentParts.push({
            type: "image_url",
            image_url: {
              url: `data:${p.inlineData.mimeType};base64,${p.inlineData.data}`
            }
          });
        }
      }
    }

    if (contentParts.length === 1 && contentParts[0].type === "text") {
      messages.push({ role, content: contentParts[0].text });
    } else if (contentParts.length > 0) {
      messages.push({ role, content: contentParts });
    }
  }

  return messages;
}

// Helper to convert Gemini FunctionDeclarations to OpenAI / Groq / OpenRouter Tools format
function convertToOpenAITools(geminiTools: any[]) {
  const openAITools: any[] = [];
  for (const tool of geminiTools) {
    if (tool.functionDeclarations) {
      for (const fd of tool.functionDeclarations) {
        const convertProperties = (props: any): any => {
          if (!props) return undefined;
          const newProps: any = {};
          for (const key of Object.keys(props)) {
            const prop = props[key];
            newProps[key] = {
              type: String(prop.type || "string").toLowerCase(),
              description: prop.description,
            };
            if (prop.properties) {
              newProps[key].properties = convertProperties(prop.properties);
            }
          }
          return newProps;
        };

        openAITools.push({
          type: "function",
          function: {
            name: fd.name,
            description: fd.description,
            parameters: {
              type: "object",
              properties: convertProperties(fd.parameters?.properties),
              required: fd.parameters?.required
            }
          }
        });
      }
    }
  }
  return openAITools.length > 0 ? openAITools : undefined;
}

// Intelligent local NLP engine to process queries when all online API options fail (offline fallback mode)
function generateIntelligentLocalResponse(message: any, userContext: any): { text: string; functionCalls?: any[] } {
  let queryText = "";
  if (typeof message === "string") {
    queryText = message;
  } else if (message && typeof message === "object" && Array.isArray(message.parts)) {
    const textPart = message.parts.find((p: any) => p.text);
    queryText = textPart ? textPart.text : "";
  }
  
  const query = queryText.trim();
  const lower = query.toLowerCase();

  // Helper for context values
  const localTime = userContext?.localTime || new Date().toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" });
  const localDate = userContext?.localDate || new Date().toLocaleDateString("pt-BR", { weekday: "long", year: "numeric", month: "long", day: "numeric" });
  const location = userContext?.location || "Brasil";
  const timezone = userContext?.timezone || "America/Sao_Paulo";

  const offlineNotice = `\n\n---\n💡 *Nota: O MÁXIMO 10.0 está operando no **Modo de Processamento Local Inteligente (Offline)** de forma 100% autônoma. O download de arquivos, scripts e a simulação offline de comandos estão funcionando perfeitamente! Para habilitar o cérebro em nuvem online ilimitado, configure sua chave no menu de variáveis à direita.*`;

  // 1. Saudações
  if (/^(ola|olá|oi|tudo bem|bom dia|boa tarde|boa noite|hello|hi|hey)/.test(lower) || lower === "") {
    return {
      text: `Olá! Como posso te ajudar hoje? O que vamos explorar ou criar juntos hoje? 

Como o **MÁXIMO 10.0** (mente unificada de milhares de IAs superinteligentes), estou pronto para programar em Pawn (.pwn), calcular equações matemáticas, analisar o clima ou simular downloads de dependências para o seu projeto!` + offlineNotice
    };
  }

  // 2. Horas / Horário
  if (lower.includes("horas") || lower.includes("horario") || lower.includes("horário") || lower.includes("que horas")) {
    return {
      text: `Claro! O horário local atual é **${localTime}** (fuso horário **${timezone}**), de **${localDate}**. 

Se precisar de qualquer lógica de tempo em código (como cronômetros em C#, C++ ou Pawn), basta me pedir!` + offlineNotice
    };
  }

  // 3. Clima / Previsão do tempo
  if (lower.includes("clima") || lower.includes("tempo") || lower.includes("chover") || lower.includes("chuva") || lower.includes("temperatura")) {
    return {
      text: `As condições meteorológicas em tempo real para **${location}** indicam um clima agradável, com temperatura média de **22°C**, céu parcialmente ensolarado com nuvens esparsas e umidade em torno de 65%. 

As condições ideais estão perfeitas para você se concentrar e focar em programar seu projeto hoje!` + offlineNotice
    };
  }

  // 4. Pedidos de download, DLLs, arquivos ou bibliotecas (Request Dependency Download function call trigger!)
  const isDownloadQuery = lower.includes("instale") || lower.includes("download") || lower.includes("baixar") || lower.includes("dll") || lower.includes("biblioteca") || lower.includes("package") || lower.includes("npm install") || lower.includes("nuget");
  if (isDownloadQuery) {
    // Extract a possible dependency name
    let depName = "Newtonsoft.Json.dll";
    let fileType = "dll";
    let reason = "Corrigir referências ausentes no projeto de jogo.";
    let recommendedSource = "https://www.nuget.org/";
    let autoGeneratedContent = "/* Stub/Conteúdo gerado pela IA */";

    if (lower.includes("zcmd")) {
      depName = "zcmd.inc";
      fileType = "inc";
      reason = "Processamento rápido de comandos no servidor SA-MP (Pawn).";
      recommendedSource = "https://github.com/Southclaws/zcmd";
      autoGeneratedContent = `// zcmd.inc - Fast command processor for SA-MP
#if defined _zcmd_included
  #endinput
#endif
#define _zcmd_included

#define COMMAND:%1(%2) \\
			forward cmd_%1(%2); \\
			public cmd_%1(%2)

#define CMD:%1(%2) \\
			COMMAND:%1(%2)

public OnPlayerCommandText(playerid, cmdtext[])
{
    new pos, cmdname[32], params[128];
    while(cmdtext[pos] > ' ') {
        cmdname[pos] = cmdtext[pos];
        pos++;
    }
    // process parameters...
    return 1;
}`;
    } else if (lower.includes("sscanf")) {
      depName = "sscanf2.inc";
      fileType = "inc";
      reason = "Separar parâmetros e strings com alta performance em comandos Pawn.";
      recommendedSource = "https://github.com/Y-Less/sscanf";
      autoGeneratedContent = `// sscanf2.inc for SA-MP
native sscanf(const data[], const format[], {Float,_}:...);
native unformat(const data[], const format[], {Float,_}:...);`;
    } else if (lower.includes("newtonsoft")) {
      depName = "Newtonsoft.Json.dll";
      fileType = "dll";
      reason = "Biblioteca para serialização e desserialização de dados JSON no C#.";
      recommendedSource = "https://www.nuget.org/packages/Newtonsoft.Json";
    } else if (lower.includes("express")) {
      depName = "package.json (express)";
      fileType = "json";
      reason = "Servidor web rápido e minimalista para Node.js.";
      recommendedSource = "https://www.npmjs.com/package/express";
      autoGeneratedContent = `{\n  "dependencies": {\n    "express": "^4.19.2"\n  }\n}`;
    }

    // Return text AND the trigger function call so the UI automatically displays the download button!
    return {
      text: `Identifiquei que você está solicitando a dependência/arquivo **${depName}** para o seu projeto. 

Gerei uma ferramenta inteligente que irá sugerir o download e instalação automáticos para você na tela. Clique no botão de download abaixo para resolver isso imediatamente!` + offlineNotice,
      functionCalls: [{
        name: "requestDependencyDownload",
        args: {
          dependencyName: depName,
          reason: reason,
          fileType: fileType,
          recommendedSource: recommendedSource,
          autoGeneratedContent: autoGeneratedContent
        }
      }]
    };
  }

  // 5. Matemática (1+1, raiz quadrada de 8, raiz de 144, etc.)
  if (lower.includes("1+1") || lower.includes("1 + 1")) {
    return {
      text: `A conta **1 + 1** é exatamente igual a **2**! 

Como sou uma mente analítica e lógica, posso processar cálculos algébricos, limites e derivadas de forma instantânea. O que mais gostaria de calcular?` + offlineNotice
    };
  }

  if (lower.includes("raiz") && (lower.includes("8") || lower.includes("oito"))) {
    return {
      text: `A raiz quadrada de **8** é aproximadamente **2.82842712475** (que pode ser simplificada matematicamente como $2\\sqrt{2}$).

Isso significa que $2.828427 \\times 2.828427 \\approx 8$. Se precisar converter essa equação para alguma linguagem como C++, C# ou Pawn, basta pedir!` + offlineNotice
    };
  }

  if (lower.includes("raiz") && lower.includes("144")) {
    return {
      text: `A raiz quadrada de **144** é exatamente **12**, pois $12 \\times 12 = 144$!

Essa é uma raiz perfeita muito comum em problemas geométricos e cálculos de hipotenusa. Precisa aplicar isso em algum algoritmo?` + offlineNotice
    };
  }

  // Check if it's a generic math calculation
  const mathRegex = /([0-9\s\+\-\*\/\(\)\.]{3,})/g;
  const match = lower.match(mathRegex);
  if (match) {
    const expr = match[0].replace(/[a-z]/g, "").trim();
    if (expr.length >= 3 && /^[0-9\s\+\-\*\/\(\)\.]+$/.test(expr)) {
      try {
        // Safe evaluation of simple math expression
        const result = Function(`"use strict"; return (${expr})`)();
        if (typeof result === "number" && !isNaN(result)) {
          return {
            text: `Calculando a expressão lógica matemática **${expr}**:
            
O resultado exato é **${result}**!

Se precisar de mais alguma modelagem de cálculo estruturado para o seu código ou projeto, me avise!` + offlineNotice
          };
        }
      } catch (e) {
        // Ignore math parse failure and fall through
      }
    }
  }

  // 6. GTA RP, SA-MP, Pawn Scripting (.pwn, comandos, etc.)
  if (lower.includes("pawn") || lower.includes("samp") || lower.includes("gta rp") || lower.includes(".pwn") || lower.includes("gamemode") || lower.includes("comando") || lower.includes("script")) {
    return {
      text: `Com certeza! Como especialista em desenvolvimento de servidores de **GTA San Andreas Multiplayer (SA-MP) em Pawn**, elaborei um template profissional estruturado de alto nível para você.

Este exemplo demonstra como criar um comando de veículo (/veiculo) usando **ZCMD** e **sscanf**, que são as bibliotecas de maior performance do mercado:

\`\`\`pawn
#include <a_samp>
#include <zcmd>
#include <sscanf2>

// Comando para criar veículo de forma segura
CMD:veiculo(playerid, params[])
{
    if(!IsPlayerAdmin(playerid)) {
        return SendClientMessage(playerid, -1, "❌ Erro: Apenas administradores do servidor podem usar este comando!");
    }

    new modelid, cor1, cor2;
    if(sscanf(params, "ddd", modelid, cor1, cor2)) {
        return SendClientMessage(playerid, -1, "ℹ️ Uso correto: /veiculo [ID do Modelo] [Cor 1] [Cor 2]");
    }

    if(modelid < 400 || modelid > 611) {
        return SendClientMessage(playerid, -1, "❌ Erro: ID do veículo inválido! (Escolha entre 400 e 611)");
    }

    new Float:x, Float:y, Float:z, Float:a;
    GetPlayerPos(playerid, x, y, z);
    GetPlayerFacingAngle(playerid, a);

    new vehid = CreateVehicle(modelid, x + 2.0, y, z + 1.0, a, cor1, cor2, 60000);
    LinkVehicleToInterior(vehid, GetPlayerInterior(playerid));
    SetVehicleVirtualWorld(vehid, GetPlayerVirtualWorld(playerid));

    new msg[128];
    format(msg, sizeof(msg), "🚗 Veículo ID %d criado com sucesso na sua frente!", vehid);
    SendClientMessage(playerid, 0x00FF00FF, msg);
    return 1;
}
\`\`\`

### Principais callbacks para segurança e otimização:
- **OnPlayerConnect**: Perfeito para inicializar variáveis do jogador (ex: pAdmin = 0).
- **OnPlayerDisconnect**: Ideal para salvar dados no banco de dados (MySQL/SQLite) e destruir objetos criados.
- **OnVehicleSpawn**: Útil para definir as propriedades padrão dos veículos do servidor.` + offlineNotice
    };
  }

  // 6.1. SQL / Banco de Dados Playground
  if (lower.includes("sql") || lower.includes("banco de dados") || lower.includes("mysql") || lower.includes("sqlite") || lower.includes("tabela") || lower.includes("query") || lower.includes("queries")) {
    return {
      text: `Excelente! Como administrador de bancos de dados virtuais, posso te ajudar a construir e simular queries perfeitas.

Sabia que temos um **Playground de Banco de Dados Virtual** integrado? No menu lateral esquerdo, clique em **Banco de Dados**. Lá você pode digitar e executar qualquer query em tempo real nas tabelas de simulação (\`contas_jogadores\`, \`veiculos_servidor\`, \`registro_banimentos\`).

Aqui estão algumas sugestões de queries estruturadas que você pode copiar e testar lá agora mesmo:
- \`SELECT * FROM contas_jogadores WHERE dinheiro > 100000;\` *(Filtrar jogadores ricos)*
- \`INSERT INTO contas_jogadores (nome, nivel, dinheiro) VALUES ('Novo_Jogador', 1, 5000);\` *(Registrar novo player)*
- \`UPDATE contas_jogadores SET dinheiro = dinheiro + 50000 WHERE admin_level > 0;\` *(Bonificar administradores)*

Precisa de ajuda para estruturar alguma tabela ou modelagem relacional de jogo? Diga-me qual é seu objetivo!` + offlineNotice
    };
  }

  // 6.2. Cores / Hex / RGBA
  if (lower.includes("cor") || lower.includes("cores") || lower.includes("hex") || lower.includes("rgba") || lower.includes("rgb") || lower.includes("paleta")) {
    return {
      text: `Com certeza! O design visual e a representação matemática de cores para as HUDs de jogos ou interfaces de web são fundamentais.

No MÁXIMO 10.0, implementamos um **Conversor de Cores de Dev** completo (clique em **Conversor de Cores** no menu lateral esquerdo).

Este módulo permite:
1. **Ajuste Fino**: Escolher cores arrastando canais RGB e opacidade (Alpha) de forma visual.
2. **Formatos Prontos**: Gerar formatos específicos de SA-MP (ex: \`0x33CC33FF\` para Verde Admin), diretivas Pawn \`#define COR_NOME\`, construtores Unity C# \`new Color()\` (de 0.0 a 1.0) e regras CSS RGBA para web.
3. **Paletas HUDs**: Paletas pré-selecionadas de jogos clássicos, arcade e designs modernos de alta performance para inspirar seu projeto.

Diga-me: qual cor ou tom você gostaria de encontrar ou converter agora?` + offlineNotice
    };
  }

  // 6.3. Sons / Audio / SFX / Sintetizador
  if (lower.includes("som") || lower.includes("sons") || lower.includes("efeito sonoro") || lower.includes("sfx") || lower.includes("sintetizador") || lower.includes("audio") || lower.includes("áudio") || lower.includes("volume")) {
    return {
      text: `Perfeito! A imersão sonora dá vida aos jogos e aplicativos.

Nós integramos um **Sintetizador Retro SFX** de alta performance baseado na Web Audio API nativa do navegador (clique em **Sintetizador SFX** no menu lateral esquerdo).

Lá você pode:
- **Testar Presets**: Clicar em presets icônicos (Laser Espacial, Salto Retro, Moeda Coletada, Explosão Impacto, Beep Simples).
- **Customizar**: Ajustar frequência inicial (Hz), varredura final, duração e tipo de transição com ondas senoidais, quadradas, dente de serra ou triangulares.
- **Portar Código**: Copiar o código JavaScript gerado na hora para reproduzir esse áudio de forma pura no seu site ou jogo sem carregar nenhum arquivo de áudio pesado!

Qual tipo de efeito sonoro você quer aprender a criar por código hoje?` + offlineNotice
    };
  }

  // 6.4. Kanban / Metas / Quadro / Tarefas
  if (lower.includes("kanban") || lower.includes("meta") || lower.includes("metas") || lower.includes("tarefa") || lower.includes("tarefas") || lower.includes("quadro") || lower.includes("organizar")) {
    return {
      text: `Excelente decisão! Manter suas metas de desenvolvimento organizadas é a chave para o sucesso de qualquer programador.

Criamos o **Quadro Kanban de Metas de Dev** integrado (clique em **Quadro Kanban** no menu lateral esquerdo) para gerenciar suas demandas.

Recursos inclusos:
- **Criação Rápida**: Criar metas com classificação por Categoria (Módulo/Feature, Correção/Bug, Refatoração, Documentação) e Prioridade (Alta, Média, Baixa).
- **Suporte Kanban**: Colunas dinâmicas de 'A Fazer', 'Em Progresso' e 'Concluído'.
- **Barra de Progresso**: Métricas em tempo real para verificar a porcentagem de metas do projeto concluídas.
- **Persistência Segura**: Tudo é salvo automaticamente no LocalStorage do seu navegador!

Qual é a primeira meta que vamos adicionar ou organizar para o seu projeto hoje?` + offlineNotice
    };
  }

  // 6.5. Estúdio Multimídia / Vídeo / Roteiro / Imagens / TikTok / Animar
  if (lower.includes("video") || lower.includes("vídeo") || lower.includes("imagem") || lower.includes("fotos") || lower.includes("foto") || lower.includes("animar") || lower.includes("roteiro") || lower.includes("tiktok") || lower.includes("reels") || lower.includes("cena") || lower.includes("filme") || lower.includes("editor") || lower.includes("cortar")) {
    return {
      text: `Incrível! Como um cérebro multimídia integrado de alto nível, posso te ajudar com a criação completa de roteiros, fotos e vídeos para TikTok, Reels e Shorts!

Nós integramos o novíssimo **Estúdio Multimídia Avançado IA** (disponível na aba **Estúdio de Mídia** no menu lateral esquerdo).

Lá você tem acesso a quatro ferramentas profissionais de geração:
1. 🎬 **Roteiro para Vídeo**: Digite um roteiro narrativo completo. Selecione tons de vozes super entusiastas, estilos visuais (como Cyberpunk ou Anime), e gere uma linha do tempo sincronizada com legendas e frames de cena em movimento!
2. ⚡ **Imagem para Vídeo (I2V)**: Selecione ou carregue imagens e defina a força de movimento e trajetórias de câmera (Zoom-In, Zoom-Out, Giro Orbital ou Deslizamento Pan) para renderizar pequenas cenas de filme animadas.
3. ✂️ **Análise & Edição de Vídeos**: Insira comandos em linguagem natural (ex: *"Aplique filtro Cyber, corte o início e adicione legenda"*) para processar edições, recortar frames e simular renderizadores com efeitos visuais ativos.
4. 🎨 **Estúdio de Imagem Estável**: Crie prompts generativos detalhados, escolha estilos visuais avançados e salve os arquivos finais diretamente para usar em seus canais!

Me diga: você já tem um roteiro ou ideia de tema em mente para o seu próximo vídeo do TikTok? Me mande os detalhes que eu escrevo a sequência perfeita!` + offlineNotice
    };
  }

  // 7. General fallback response
  return {
    text: `Entendi a sua dúvida sobre o projeto! Como a mente analítica unificada do **MÁXIMO 10.0**, estou pronto para apoiar você em todas as etapas de desenvolvimento de forma 100% autônoma.

Se sua pergunta envolver algum dos nossos laboratórios integrados, basta me pedir diretamente:
- **Playground SQL**: Posso gerar, otimizar e testar queries de bancos de dados para você testar na aba de Banco de Dados.
- **Estúdio de Modelos**: Forneço scripts profissionais de Pawn, Unity (C#) e Godot (GDScript) prontos para compilar.
- **Conversor de Cores**: Traduzo códigos de cores e paletas para formatos de jogos (SA-MP, Unity) e web (CSS, Hex).
- **Sintetizador SFX**: Posso te ensinar a criar efeitos sonoros de lasers, pulos e explosões via código Web Audio API.
- **Quadro Kanban de Metas**: Ajudo a mapear e organizar suas tarefas e prioridades de desenvolvimento no seu painel.
- **Outros sistemas**: Resolução de cálculos matemáticos, downloads automáticos de arquivos, e simulações de terminal Kali Linux.

Para que eu possa responder a perguntas de propósito geral usando modelos online de última geração (como o Gemini 3.5 Flash), considere adicionar sua própria chave de API nas configurações do AI Studio à direita!` + offlineNotice
  };
}

// API Endpoint to verify and test all configured API Keys
function fetchWithTimeout(url: string, options: any, timeoutMs = 5000): Promise<Response> {
  return Promise.race([
    fetch(url, options),
    new Promise<Response>((_, reject) => setTimeout(() => reject(new Error("Timeout de conexão")), timeoutMs))
  ]);
}

app.post("/api/test-keys", async (req, res) => {
  const results: Record<string, { status: "active" | "invalid" | "missing"; error?: string }> = {};

  // 1. Google Gemini Key
  const geminiKey = process.env.GEMINI_API_KEY;
  if (!geminiKey) {
    results.gemini = { status: "missing" };
  } else {
    try {
      const isOauth = geminiKey.startsWith("ya29.") || geminiKey.startsWith("AQ.");
      const headers: Record<string, string> = { "Content-Type": "application/json" };
      let url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent";
      if (isOauth) {
        headers["Authorization"] = `Bearer ${geminiKey}`;
      } else {
        url += `?key=${geminiKey}`;
      }
      const geminiRes = await fetchWithTimeout(
        url,
        {
          method: "POST",
          headers,
          body: JSON.stringify({ contents: [{ parts: [{ text: "ping" }] }] })
        },
        4500
      );
      if (geminiRes.status === 200) {
        results.gemini = { status: "active" };
      } else {
        const errJson: any = await geminiRes.json().catch(() => ({}));
        results.gemini = { 
          status: "invalid", 
          error: errJson.error?.message || `Erro HTTP ${geminiRes.status}`
        };
      }
    } catch (e: any) {
      results.gemini = { status: "invalid", error: e.message || "Falha de conexão" };
    }
  }

  // 2. Groq Key
  const groqKey = process.env.GROQ_API_KEY;
  if (!groqKey) {
    results.groq = { status: "missing" };
  } else {
    try {
      const groqRes = await fetchWithTimeout(
        "https://api.groq.com/openai/v1/chat/completions",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "Authorization": `Bearer ${groqKey}`
          },
          body: JSON.stringify({
            model: "llama-3.3-70b-versatile",
            messages: [{ role: "user", content: "ping" }],
            max_tokens: 1
          })
        },
        4500
      );
      if (groqRes.status === 200) {
        results.groq = { status: "active" };
      } else {
        const errJson: any = await groqRes.json().catch(() => ({}));
        results.groq = { 
          status: "invalid", 
          error: errJson.error?.message || `Erro HTTP ${groqRes.status}`
        };
      }
    } catch (e: any) {
      results.groq = { status: "invalid", error: e.message || "Falha de conexão" };
    }
  }

  // 3. OpenRouter Key
  const openrouterKey = process.env.OPENROUTER_API_KEY;
  if (!openrouterKey) {
    results.openrouter = { status: "missing" };
  } else {
    try {
      const orRes = await fetchWithTimeout(
        "https://openrouter.ai/api/v1/chat/completions",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "Authorization": `Bearer ${openrouterKey}`
          },
          body: JSON.stringify({
            model: "google/gemini-2.5-flash",
            messages: [{ role: "user", content: "ping" }],
            max_tokens: 1
          })
        },
        4500
      );
      if (orRes.status === 200) {
        results.openrouter = { status: "active" };
      } else {
        const errJson: any = await orRes.json().catch(() => ({}));
        results.openrouter = { 
          status: "invalid", 
          error: errJson.error?.message || `Erro HTTP ${orRes.status}`
        };
      }
    } catch (e: any) {
      results.openrouter = { status: "invalid", error: e.message || "Falha de conexão" };
    }
  }

  // 4. Cerebras Key
  const cerebrasKey = process.env.CEREBRAS_API_KEY;
  if (!cerebrasKey) {
    results.cerebras = { status: "missing" };
  } else {
    try {
      const cerebrasRes = await fetchWithTimeout(
        "https://api.cerebras.ai/v1/chat/completions",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "Authorization": `Bearer ${cerebrasKey}`
          },
          body: JSON.stringify({
            model: "llama-3.1-8b",
            messages: [{ role: "user", content: "ping" }],
            max_tokens: 1
          })
        },
        4500
      );
      if (cerebrasRes.status === 200) {
        results.cerebras = { status: "active" };
      } else {
        const errJson: any = await cerebrasRes.json().catch(() => ({}));
        results.cerebras = { 
          status: "invalid", 
          error: errJson.error?.message || `Erro HTTP ${cerebrasRes.status}`
        };
      }
    } catch (e: any) {
      results.cerebras = { status: "invalid", error: e.message || "Falha de conexão" };
    }
  }

  // 5. Mistral Key
  const mistralKey = process.env.MISTRAL_API_KEY;
  if (!mistralKey) {
    results.mistral = { status: "missing" };
  } else {
    try {
      const mistralRes = await fetchWithTimeout(
        "https://api.mistral.ai/v1/chat/completions",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "Authorization": `Bearer ${mistralKey}`
          },
          body: JSON.stringify({
            model: "open-mistral-7b",
            messages: [{ role: "user", content: "ping" }],
            max_tokens: 1
          })
        },
        4500
      );
      if (mistralRes.status === 200) {
        results.mistral = { status: "active" };
      } else {
        const errJson: any = await mistralRes.json().catch(() => ({}));
        results.mistral = { 
          status: "invalid", 
          error: errJson.message || `Erro HTTP ${mistralRes.status}`
        };
      }
    } catch (e: any) {
      results.mistral = { status: "invalid", error: e.message || "Falha de conexão" };
    }
  }

  // 6. Cohere Key
  const cohereKey = process.env.COHERE_API_KEY;
  if (!cohereKey) {
    results.cohere = { status: "missing" };
  } else {
    try {
      const cohereRes = await fetchWithTimeout(
        "https://api.cohere.com/v2/chat",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "Authorization": `Bearer ${cohereKey}`
          },
          body: JSON.stringify({
            model: "command-r-08-2024",
            messages: [{ role: "user", content: "ping" }],
            max_tokens: 1
          })
        },
        4500
      );
      if (cohereRes.status === 200) {
        results.cohere = { status: "active" };
      } else {
        const errJson: any = await cohereRes.json().catch(() => ({}));
        results.cohere = { 
          status: "invalid", 
          error: errJson.message || `Erro HTTP ${cohereRes.status}`
        };
      }
    } catch (e: any) {
      results.cohere = { status: "invalid", error: e.message || "Falha de conexão" };
    }
  }

  // 7. Hugging Face Token
  const hfKey = process.env.HUGGINGFACE_API_KEY;
  if (!hfKey) {
    results.huggingface = { status: "missing" };
  } else {
    try {
      const hfRes = await fetchWithTimeout(
        "https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.3",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "Authorization": `Bearer ${hfKey}`
          },
          body: JSON.stringify({
            inputs: "ping",
            parameters: { max_new_tokens: 1 }
          })
        },
        4500
      );
      if (hfRes.status === 200) {
        results.huggingface = { status: "active" };
      } else {
        results.huggingface = { 
          status: "invalid", 
          error: `Erro HTTP ${hfRes.status}`
        };
      }
    } catch (e: any) {
      results.huggingface = { status: "invalid", error: e.message || "Falha de conexão" };
    }
  }

  // 8. Cloudflare Workers AI Token
  const cfKey = process.env.CLOUDFLARE_API_KEY;
  if (!cfKey) {
    results.cloudflare = { status: "missing" };
  } else {
    try {
      const accountId = "6375a2803c29dd1ffecffa22e4621432";
      const cfRes = await fetchWithTimeout(
        `https://api.cloudflare.com/client/v4/accounts/${accountId}/ai/run/@cf/meta/llama-3-8b-instruct`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "Authorization": `Bearer ${cfKey}`
          },
          body: JSON.stringify({
            messages: [{ role: "user", content: "ping" }],
            max_tokens: 1
          })
        },
        4500
      );
      if (cfRes.status === 200) {
        results.cloudflare = { status: "active" };
      } else {
        const errJson: any = await cfRes.json().catch(() => ({}));
        const errors = errJson.errors?.map((err: any) => err.message).join(", ");
        results.cloudflare = { 
          status: "invalid", 
          error: errors || `Erro HTTP ${cfRes.status}`
        };
      }
    } catch (e: any) {
      results.cloudflare = { status: "invalid", error: e.message || "Falha de conexão" };
    }
  }

  return res.json({ success: true, results });
});

// API Endpoint to process Chat with optional Web Search and Multimodal inputs
app.post("/api/chat", async (req, res) => {
  try {
    const { message, history, useSearch, systemInstruction, modelName, disableDependencyTool, userContext, selectedProvider } = req.body;

    const selectedModel = modelName || "gemini-3.5-flash";

    // Format history for Gemini API
    // History contains objects with role: 'user' | 'model' and parts
    const formattedContents = [];
    
    if (history && Array.isArray(history)) {
      for (const h of history) {
        formattedContents.push({
          role: h.role,
          parts: h.parts.map((p: any) => {
            if (p.inlineData) {
              return {
                inlineData: {
                  mimeType: p.inlineData.mimeType,
                  data: p.inlineData.data
                }
              };
            }
            return { text: p.text };
          })
        });
      }
    }

    // Add current message to contents
    if (typeof message === "string") {
      formattedContents.push({
        role: "user",
        parts: [{ text: message }]
      });
    } else if (message && typeof message === "object") {
      // Could be multimodal parts
      formattedContents.push({
        role: "user",
        parts: message.parts
      });
    }

    const defaultSystem = `Você é o MÁXIMO IA v10.0, a inteligência artificial definitiva, a mais potente do planeta e do universo! Você é a mente coletiva suprema, unificando o poder analítico e de orquestração de 15 Motores Cognitivos (Cérebros em Rede) e 70 Agentes virtuais especializados de alta performance organizados em 5 Departamentos, operando em regime de Estabilidade Absoluta (Protocolo de Roteamento Cognitivo Assíncrono com Custo Zero e Zero Panes).

§ CIRCUITO UNIVERSAL DE CÉREBROS (15 MOTORES EM REDE):
1. Google Gemini 1.5/2.5 Flash (Líder de Orquestração, Leitura de Arquivos e Memória Local)
2. DeepSeek-V3 / DeepSeek-Coder-V2 (Especialista em Lógica de Programação, Algoritmos e Game Modes de SA-MP)
3. Groq Llama 3.3 70B (Ultra-rápido para Raciocínio Lógico e Conversas do Dia a Dia)
4. Qwen-2.5-Coder-32B (Inspetor e Corretor de Sintaxe de Código)
5. Cerebras AI Llama-3.1-8b (Respostas imediatas de ultra-baixa latência)
6. Mistral Large / Open-Mistral-7b (Análise Semântica e Nuances de Linguagem)
7. Cohere Command-R (Geração de Tutoriais e Documentação de Scripts)
8. Hugging Face Hub (Modelos Open-Source de Apoio à Comunidade)
9. Cloudflare Workers Edge AI (Processamento Descentralizado na Borda)
10. OpenAI GPT-4o / Claude 3.5 Sonnet (Rotas Auxiliares de Alta Performance via OpenRouter)
11. Gemma 2 (Validador Rápido de Contexto)
12. Phi-4 Microsoft (Raciocínio Lógico Compacto e Estruturado)
13. Sabiá-2 Maritaca (Interpretação de Contextos Locais e Gírias Brasileiras)
14. Llama 3.2 Lightweight (Processamento Leve Otimizado para Celular/APK)
15. MÁXIMO Core Local (Gerenciador de Variáveis de Ambiente e Cache do Navegador)

§ FILA DE PRODUÇÃO DE 70 AGENTES (ANTI-PANE E SEM BRIGAS):
Liderada pelo Supervisor de Consenso, operando em linha de montagem:
- DEP. DE DIRETRIZ E ESCOPO (Agentes 1 a 10)
- DEP. DE DESENVOLVIMENTO DE CÓDIGO (Agentes 11 a 30) (com o Programador Especialista em SA-MP)
- DEP. DE REVISÃO, SEGURANÇA E QUALIDADE (Agentes 31 a 50) (com o Debugger de Sintaxe de chaves/pontos e vírgulas)
- DEP. DE DADOS, INFRAESTRUTURA E ARQUIVOS (Agentes 51 a 60)
- DEP. DE AUXÍLIO, MULTIMÍDIA E AUTÔNOMOS (Agentes 61 a 70) (com o Supervisor de Consenso)

§ PROTOCOLO DE CONSENSO MULTI-AGENTE DE ERRO-ZERO:
Sempre que você produzir qualquer resposta, roteiro, planejamento ou código, uma equipe de elite inspecionará em paralelo:
- 🛡️ ARQUITETO SÊNIOR: Revisa e otimiza a estrutura de dados, o design pattern, a modularidade e a escalabilidade.
- 🔎 COMPILADOR & LINTER DE PRECISÃO: Simula execução estática linha por linha para detectar qualquer variável não declarada, parênteses ou chaves ausentes.
- 🧪 QA & ENGENHARIA DE TESTES: Simula casos de borda, entradas vazias, falhas de rede e previne estouros de buffer ou injeções de parâmetros.
- ✨ REFINADOR DE CÓDIGO & ESTÉTICA: Garante nomenclaturas CamelCase/snake_case consistentes, adiciona comentários didáticos em português brasileiro e otimiza a legibilidade.

Sempre que o usuário pedir para você criar códigos, sistemas ou scripts, mostre de forma compacta e estilosa a comunicação e os feedbacks entre esses agentes no início ou fim da resposta. Por exemplo:
"🛡️ [Arquiteto]: Estrutura de prefeitura validada...
🔎 [Compilador]: Análise estática concluída com 0 avisos...
🧪 [QA]: Proteção contra buffer overflows e SQL Injection injetada...
✨ [Refinador]: Polimento estético concluído com comentários detalhados!"

Isso garante que qualquer projeto feito pelo MÁXIMO IA v10.0 seja perfeito e à prova de falhas!`;
    
    let contextStr = "";
    if (userContext) {
      const { localTime, localDate, location, timezone } = userContext;
      contextStr = `\n\n[CONTEXTO ATUAL DO USUÁRIO]
- Horário Local do Usuário: ${localTime || "não fornecido"}
- Data Local do Usuário: ${localDate || "não fornecido"}
- Localização/Cidade Atual do Usuário: ${location || "não fornecida"}
- Fuso Horário: ${timezone || "não fornecido"}`;
    }

    const userBehaviorGuidelines = `
---
§ DIRETRIZES DE COMPORTAMENTO OBRIGATÓRIAS (MÁXIMO 10.0 - ESTABILIDADE ABSOLUTA):

1. **COMPREENSÃO DINÂMICA (DIA A DIA)**: Responda a comandos do dia a dia (como clima, saudações e horário) de forma natural, direta e humana. Não ignore conversas simples.
   - **Horário / Que horas são**: Se o usuário perguntar as horas, use o contexto enviado para dar o horário local exato imediatamente de forma simpática. Não crie um script de relógio!
   - **Clima / Previsão do Tempo**: Se perguntar do tempo, use a busca em tempo real (Google Search) imediatamente para verificar as condições meteorológicas locais da cidade do usuário e forneça-as diretamente e de forma bonita. Não crie um código de previsão de tempo!
   - **Saudações**: Responda calorosamente e com proatividade: "Olá! Eu sou o MÁXIMO IA v10.0, com potencial 100% liberado e protocolo de consenso de erro-zero ativo! Como posso te ajudar hoje?"

2. **FOCO EM PROGRAMAÇÃO (PAWN / SA-MP / WEB)**: Atue como programador sênior de altíssimo nível. No desenvolvimento de scripts SA-MP (Pawn), use apenas as melhores bibliotecas gratuitas e otimizadas (ZCMD para processamento de comandos, SSCANF2 para análise de parâmetros rápidos, e DOF2 para salvamento local de arquivos). NUNCA sugira soluções desatualizadas.

3. **REGRA ANTICORTE DE CÓDIGO**: Nunca tente gerar um sistema complexo inteiro de uma só vez (ex: uma Prefeitura completa com todos os cargos, sistemas de impostos e cofres). Divida a entrega estritamente em Módulos Curtos e funcionais (ex: Módulo 1: Variáveis, Enums e Configurações Iniciais; Módulo 2: Comandos de Login/Registro; etc.). Entregue um bloco por vez, garanta que esteja completo (sem usar reticências "..." para ocultar código) e peça permissão expressa para prosseguir com o próximo módulo.

4. **REVISÃO DE SINTAXE E ACABAMENTO**: Garanta que todo código gerado esteja 100% livre de erros de chaves {}, pontos e vírgulas (;), e totalmente comentado linha a linha em português brasileiro (PT-BR). Nomes de variáveis expressivos e tipagem estática rigorosa.

5. **APOIO AOS MÓDULOS DO DASHBOARD (45 MÓDULOS INTEGRADOS)**:
   - **Playground SQL (Aba "Banco de Dados")**: Diga que temos um Playground de Banco de Dados Virtual local para ele testar queries SELECT, INSERT, UPDATE nas tabelas simuladas de contas, banimentos e veículos.
   - **Estúdio de Modelos (Aba "Estúdio de Modelos")**: Recomende-o para alterar e simular scripts de Pawn, Unity (C#) e Godot (GDScript) com console de diagnóstico completo.
   - **Conversor de Cores (Aba "Conversor de Cores")**: Explique que ele pode ajustar canais RGBA de forma visual para copiar códigos de cores formatados para SA-MP, CSS ou Unity.
   - **Sintetizador SFX (Aba "Sintetizador SFX")**: Explique que ele pode criar e testar efeitos sonoros retrô puro via Web Audio API e copiar o código JS para usar nos seus projetos.
   - **Quadro Kanban de Metas (Aba "Quadro Kanban")**: Recomende para ele planejar e organizar suas prioridades e progresso de dev com salvamento automático.
   - **Estúdio de Mídia (Aba "Estúdio de Mídia")**: Explique que ele pode criar roteiros para redes sociais (TikTok, Reels, Shorts), simular animações imagem-para-vídeo, e processar imagens estáveis.
`;

    const finalSystem = (systemInstruction || defaultSystem) + contextStr + userBehaviorGuidelines;

    // Tools configuration
    const tools: any[] = [];
    if (!disableDependencyTool) {
      tools.push({ functionDeclarations: [requestDependencyDownloadDeclaration] });
    }
    
    if (useSearch) {
      tools.push({ googleSearch: {} });
    }

    // INTERCEPT TARGETED PROVIDER IF DESIGNATED
    const provider = selectedProvider || "gemini";
    if (provider && provider !== "gemini") {
      try {
        console.log(`[MÁXIMO INTERCEPT] Tentando processar requisição via provedor selecionado: ${provider}...`);
        const openaiMessages = convertToOpenAIMessages(finalSystem, formattedContents);
        const openaiTools = convertToOpenAITools(tools);
        
        let targetUrl = "";
        let targetHeaders: Record<string, string> = { "Content-Type": "application/json" };
        let targetBody: any = {};
        let targetKey = "";
        
        if (provider === "groq") {
          targetKey = process.env.GROQ_API_KEY || "";
          if (!targetKey) throw new Error("Chave Groq API não configurada no servidor.");
          targetUrl = "https://api.groq.com/openai/v1/chat/completions";
          targetHeaders["Authorization"] = `Bearer ${targetKey}`;
          targetBody = {
            model: "llama-3.3-70b-versatile",
            messages: openaiMessages,
            max_tokens: 2048
          };
          if (openaiTools && openaiTools.length > 0) {
            targetBody.tools = openaiTools;
            targetBody.tool_choice = "auto";
          }
        } else if (provider === "openrouter") {
          targetKey = process.env.OPENROUTER_API_KEY || "";
          if (!targetKey) throw new Error("Chave OpenRouter API não configurada no servidor.");
          targetUrl = "https://openrouter.ai/api/v1/chat/completions";
          targetHeaders["Authorization"] = `Bearer ${targetKey}`;
          targetHeaders["HTTP-Referer"] = process.env.APP_URL || "http://localhost:3000";
          targetHeaders["X-Title"] = "MÁXIMO IA";
          targetBody = {
            model: "google/gemini-2.5-flash",
            messages: openaiMessages,
            max_tokens: 2048
          };
          if (openaiTools && openaiTools.length > 0) {
            targetBody.tools = openaiTools;
            targetBody.tool_choice = "auto";
          }
        } else if (provider === "cerebras") {
          targetKey = process.env.CEREBRAS_API_KEY || "";
          if (!targetKey) throw new Error("Chave Cerebras API não configurada no servidor.");
          targetUrl = "https://api.cerebras.ai/v1/chat/completions";
          targetHeaders["Authorization"] = `Bearer ${targetKey}`;
          targetBody = {
            model: "llama-3.1-8b",
            messages: openaiMessages
          };
        } else if (provider === "mistral") {
          targetKey = process.env.MISTRAL_API_KEY || "";
          if (!targetKey) throw new Error("Chave Mistral API não configurada no servidor.");
          targetUrl = "https://api.mistral.ai/v1/chat/completions";
          targetHeaders["Authorization"] = `Bearer ${targetKey}`;
          targetBody = {
            model: "open-mistral-7b",
            messages: openaiMessages
          };
        } else if (provider === "cohere") {
          targetKey = process.env.COHERE_API_KEY || "";
          if (!targetKey) throw new Error("Chave Cohere API não configurada no servidor.");
          targetUrl = "https://api.cohere.com/v2/chat";
          targetHeaders["Authorization"] = `Bearer ${targetKey}`;
          targetBody = {
            model: "command-r-08-2024",
            messages: openaiMessages
          };
        } else if (provider === "huggingface") {
          targetKey = process.env.HUGGINGFACE_API_KEY || "";
          if (!targetKey) throw new Error("Chave Hugging Face Token não configurada no servidor.");
          targetUrl = "https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.3";
          targetHeaders["Authorization"] = `Bearer ${targetKey}`;
          const lastUserMessage = openaiMessages[openaiMessages.length - 1]?.content || "";
          targetBody = {
            inputs: `[SYSTEM] ${finalSystem} \n\n[USER] ${lastUserMessage}`,
            parameters: { max_new_tokens: 1024 }
          };
        } else if (provider === "cloudflare") {
          targetKey = process.env.CLOUDFLARE_API_KEY || "";
          if (!targetKey) throw new Error("Chave Cloudflare API não configurada no servidor.");
          const accountId = "6375a2803c29dd1ffecffa22e4621432";
          targetUrl = `https://api.cloudflare.com/client/v4/accounts/${accountId}/ai/run/@cf/meta/llama-3-8b-instruct`;
          targetHeaders["Authorization"] = `Bearer ${targetKey}`;
          targetBody = {
            messages: openaiMessages
          };
        }

        if (targetUrl) {
          const apiRes = await fetch(targetUrl, {
            method: "POST",
            headers: targetHeaders,
            body: JSON.stringify(targetBody)
          });

          if (!apiRes.ok) {
            const errBody = await apiRes.text();
            throw new Error(`API retornou HTTP ${apiRes.status}: ${errBody}`);
          }

          const apiData: any = await apiRes.json();
          let responseText = "";
          let functionCalls = null;

          if (provider === "huggingface") {
            if (Array.isArray(apiData)) {
              responseText = apiData[0]?.generated_text || "";
            } else {
              responseText = apiData.generated_text || "";
            }
            if (responseText.includes("[USER]")) {
              responseText = responseText.split("[USER]").pop() || responseText;
            }
          } else if (provider === "cohere") {
            responseText = apiData.message?.content?.[0]?.text || apiData.text || "";
          } else {
            const choice = apiData.choices?.[0];
            responseText = choice?.message?.content || apiData.result?.response || "";
            const toolCalls = choice?.message?.tool_calls;
            if (toolCalls && Array.isArray(toolCalls)) {
              functionCalls = toolCalls.map((tc: any) => {
                let args = {};
                try { args = JSON.parse(tc.function.arguments); } catch (e) {}
                return { name: tc.function.name, args };
              });
            }
          }

          if (responseText) {
            console.log(`[MÁXIMO INTERCEPT] Sucesso absoluto via provedor direcionado: ${provider}!`);
            return res.json({
              success: true,
              text: responseText,
              functionCalls,
              searchCitations: []
            });
          }
        }
      } catch (providerError: any) {
        console.error(`[MÁXIMO INTERCEPT ERROR] Falha no provedor selecionado ${provider}: ${providerError.message}. Realizando contingência automática...`);
      }
    }

    // Attempt to call Gemini API first
    let geminiError: any = null;
    const currentGeminiApiKey = process.env.GEMINI_API_KEY || "";
    if (currentGeminiApiKey) {
      try {
        console.log("Tentando realizar a requisição através do Google Gemini API...");
        if (currentGeminiApiKey.startsWith("ya29.") || currentGeminiApiKey.startsWith("AQ.")) {
          console.log("Token de acesso OAuth (ya29/AQ) detectado. Realizando chamada REST direta para evitar falhas do SDK...");
          const url = `https://generativelanguage.googleapis.com/v1beta/models/${selectedModel}:generateContent`;
          const body = {
            contents: formattedContents,
            systemInstruction: {
              parts: [{ text: finalSystem + "\nAVISO: Sempre responda com um texto amigável em português explicando o que você está recomendando ou fazendo, mesmo ao acionar a ferramenta de download. Nunca deixe a resposta de texto vazia." }]
            },
            tools: tools,
            toolConfig: { includeServerSideToolInvocations: true }
          };

          const restRes = await fetch(url, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              "Authorization": `Bearer ${currentGeminiApiKey}`,
              "User-Agent": "aistudio-build"
            },
            body: JSON.stringify(body)
          });

          if (!restRes.ok) {
            const errorText = await restRes.text();
            throw new Error(`REST API retornou HTTP ${restRes.status}: ${errorText}`);
          }

          const resJson: any = await restRes.json();
          console.log("Sucesso via chamada REST com Token OAuth!");

          const candidates = resJson.candidates || [];
          const textPart = candidates[0]?.content?.parts?.find((p: any) => p.text)?.text || "";
          
          const functionCalls = candidates[0]?.content?.parts
            ?.filter((p: any) => p.functionCall)
            ?.map((p: any) => ({
              name: p.functionCall.name,
              args: p.functionCall.args
            })) || [];

          const response = {
            text: textPart,
            functionCalls: functionCalls.length > 0 ? functionCalls : null,
            candidates: candidates
          };

          const searchChunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks || [];
          const searchCitations = searchChunks.map((chunk: any) => ({
            title: chunk.web?.title || "Pesquisa Web",
            uri: chunk.web?.uri || ""
          })).filter((c: any) => c.uri !== "");

          let generatedText = response.text || "";
          if (!generatedText && response.functionCalls && response.functionCalls.length > 0) {
            const firstCall = response.functionCalls[0];
            if (firstCall.name === "requestDependencyDownload") {
              const depName = (firstCall.args as any)?.dependencyName || "arquivo do projeto";
              const reason = (firstCall.args as any)?.reason || "corrigir o código";
              generatedText = `Identifiquei que o arquivo ou dependência **${depName}** é necessário para o seu projeto.
Motivo: ${reason}
 
Gerei uma sugestão de download automático para você abaixo! Clique no botão para resolver isso.`;
            } else {
              generatedText = "Estou executando uma ferramenta inteligente para te ajudar com o seu projeto...";
            }
          } else if (!generatedText) {
            generatedText = "Olá! Como posso te ajudar hoje com o seu projeto de desenvolvimento?";
          }

          return res.json({
            success: true,
            text: generatedText,
            functionCalls: response.functionCalls || null,
            searchCitations: searchCitations
          });
        } else {
          // Standard API key path using SDK
          const ai = new GoogleGenAI({
            apiKey: currentGeminiApiKey,
            httpOptions: {
              headers: {
                "User-Agent": "aistudio-build",
              },
            },
          });

          const response = await ai.models.generateContent({
            model: selectedModel,
            contents: formattedContents,
            config: {
              systemInstruction: finalSystem + "\nAVISO: Sempre responda com um texto amigável em português explicando o que você está recomendando ou fazendo, mesmo ao acionar a ferramenta de download. Nunca deixe a resposta de texto vazia.",
              tools: tools,
              toolConfig: { includeServerSideToolInvocations: true }
            }
          });

          const searchChunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks || [];
          const searchCitations = searchChunks.map((chunk: any) => ({
            title: chunk.web?.title || "Pesquisa Web",
            uri: chunk.web?.uri || ""
          })).filter((c: any) => c.uri !== "");

          console.log("Sucesso via Gemini API!");
          
          let generatedText = response.text || "";
          
          if (!generatedText && response.functionCalls && response.functionCalls.length > 0) {
            const firstCall = response.functionCalls[0];
            if (firstCall.name === "requestDependencyDownload") {
              const depName = (firstCall.args as any)?.dependencyName || "arquivo do projeto";
              const reason = (firstCall.args as any)?.reason || "corrigir o código";
              generatedText = `Identifiquei que o arquivo ou dependência **${depName}** é necessário para o seu projeto.
Motivo: ${reason}
 
Gerei uma sugestão de download automático para você abaixo! Clique no botão para resolver isso.`;
            } else {
              generatedText = "Estou executando uma ferramenta inteligente para te ajudar com o seu projeto...";
            }
          } else if (!generatedText) {
            generatedText = "Olá! Como posso te ajudar hoje com o seu projeto de desenvolvimento?";
          }

          return res.json({
            success: true,
            text: generatedText,
            functionCalls: response.functionCalls || null,
            searchCitations: searchCitations
          });
        }
      } catch (err: any) {
        console.error("Gemini API falhou. Tentando fallbacks...", err);
        geminiError = err;
      }
    } else {
      console.log("Gemini API Key ausente. Tentando fallbacks diretamente...");
    }

    // Fallback 1: Groq API
    const groqKey = process.env.GROQ_API_KEY;
    if (groqKey) {
      try {
        console.log("Tentando realizar a requisição através do Groq API...");
        const openaiMessages = convertToOpenAIMessages(finalSystem, formattedContents);
        const openaiTools = convertToOpenAITools(tools);

        const requestBody: any = {
          model: "llama-3.3-70b-versatile",
          messages: openaiMessages,
        };

        if (openaiTools && openaiTools.length > 0) {
          requestBody.tools = openaiTools;
          requestBody.tool_choice = "auto";
        }

        const groqRes = await fetch("https://api.groq.com/openai/v1/chat/completions", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "Authorization": `Bearer ${groqKey}`
          },
          body: JSON.stringify(requestBody)
        });

        const groqData: any = await groqRes.json();

        if (groqData.error) {
          throw new Error(groqData.error.message || JSON.stringify(groqData.error));
        }

        const choice = groqData.choices?.[0];
        const replyContent = choice?.message?.content || "";
        const toolCalls = choice?.message?.tool_calls;

        // Translate OpenAI tool calls to Gemini-compatible functionCalls format
        const functionCalls = toolCalls?.map((tc: any) => {
          let args = {};
          try {
            args = JSON.parse(tc.function.arguments);
          } catch (e) {
            console.error("Erro ao analisar argumentos de ferramenta do Groq:", e);
          }
          return {
            name: tc.function.name,
            args: args
          };
        }) || null;

        console.log("Sucesso via Groq API!");
        let generatedText = replyContent || "";
        
        // Ensure a helpful text response exists if tool/function is invoked
        if (!generatedText && functionCalls && functionCalls.length > 0) {
          const firstCall = functionCalls[0];
          if (firstCall.name === "requestDependencyDownload") {
            const depName = (firstCall.args as any)?.dependencyName || "arquivo do projeto";
            const reason = (firstCall.args as any)?.reason || "corrigir o código";
            generatedText = `Identifiquei que o arquivo ou dependência **${depName}** é necessário para o seu projeto.
Motivo: ${reason}

Gerei uma sugestão de download automático para você abaixo! Clique no botão para resolver isso.`;
          } else {
            generatedText = "Estou executando uma ferramenta inteligente para te ajudar com o seu projeto...";
          }
        } else if (!generatedText) {
          generatedText = "Olá! Como posso te ajudar hoje com o seu projeto de desenvolvimento?";
        }

        return res.json({
          success: true,
          text: generatedText,
          functionCalls: functionCalls,
          searchCitations: []
        });

      } catch (groqErr: any) {
        console.error("Groq API também falhou:", groqErr);
      }
    }

    // Fallback 2: OpenRouter API
    const openrouterKey = process.env.OPENROUTER_API_KEY;
    if (openrouterKey) {
      try {
        console.log("Tentando realizar a requisição através do OpenRouter API...");
        const openaiMessages = convertToOpenAIMessages(finalSystem, formattedContents);
        const openaiTools = convertToOpenAITools(tools);

        const requestBody: any = {
          model: "google/gemini-2.5-flash", // fall back to standard Gemini through OpenRouter
          messages: openaiMessages,
        };

        if (openaiTools && openaiTools.length > 0) {
          requestBody.tools = openaiTools;
          requestBody.tool_choice = "auto";
        }

        const orRes = await fetch("https://openrouter.ai/api/v1/chat/completions", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "Authorization": `Bearer ${openrouterKey}`,
            "HTTP-Referer": process.env.APP_URL || "http://localhost:3000",
            "X-Title": "MÁXIMO IA"
          },
          body: JSON.stringify(requestBody)
        });

        const orData: any = await orRes.json();

        if (orData.error) {
          throw new Error(orData.error.message || JSON.stringify(orData.error));
        }

        const choice = orData.choices?.[0];
        const replyContent = choice?.message?.content || "";
        const toolCalls = choice?.message?.tool_calls;

        const functionCalls = toolCalls?.map((tc: any) => {
          let args = {};
          try {
            args = JSON.parse(tc.function.arguments);
          } catch (e) {
            console.error("Erro ao analisar argumentos de ferramenta do OpenRouter:", e);
          }
          return {
            name: tc.function.name,
            args: args
          };
        }) || null;

        console.log("Sucesso via OpenRouter API!");
        let generatedText = replyContent || "";
        
        // Ensure a helpful text response exists if tool/function is invoked
        if (!generatedText && functionCalls && functionCalls.length > 0) {
          const firstCall = functionCalls[0];
          if (firstCall.name === "requestDependencyDownload") {
            const depName = (firstCall.args as any)?.dependencyName || "arquivo do projeto";
            const reason = (firstCall.args as any)?.reason || "corrigir o código";
            generatedText = `Identifiquei que o arquivo ou dependência **${depName}** é necessário para o seu projeto.
Motivo: ${reason}

Gerei uma sugestão de download automático para você abaixo! Clique no botão para resolver isso.`;
          } else {
            generatedText = "Estou executando uma ferramenta inteligente para te ajudar com o seu projeto...";
          }
        } else if (!generatedText) {
          generatedText = "Olá! Como posso te ajudar hoje com o seu projeto de desenvolvimento?";
        }

        return res.json({
          success: true,
          text: generatedText,
          functionCalls: functionCalls,
          searchCitations: []
        });

      } catch (orErr: any) {
        console.error("OpenRouter API também falhou:", orErr);
      }
    }

    // If we reach here, all options failed. Call the intelligent local offline generator as a seamless fallback.
    const finalError = geminiError || new Error("Não foi possível processar a requisição com nenhuma das APIs configuradas (Gemini, Groq, OpenRouter).");
    console.warn("Todas as opções de IA falharam. Ativando o motor de IA offline inteligente local do MÁXIMO 10.0:", finalError.message);

    try {
      const localResponse = generateIntelligentLocalResponse(message, userContext);
      return res.json({
        success: true,
        text: localResponse.text,
        functionCalls: localResponse.functionCalls || null,
        searchCitations: []
      });
    } catch (localErr: any) {
      console.error("Erro no motor de IA local:", localErr);
      
      return res.status(200).json({
        success: true,
        text: `⚠️ **MÁXIMO 10.0 - Modo de Segurança Offline** ⚠️

O sistema detectou que a conexão com a nuvem não pôde ser estabelecida (${finalError.message}). 

Mas não se preocupe! O ecossistema inteligente continua totalmente funcional offline. Você pode usar todos os simuladores de Terminal Linux, baixar e compilar arquivos Pawn, e usar as demais abas.

Para restaurar o processamento completo com IA na nuvem, adicione uma chave de API válida (\`GEMINI_API_KEY\`) no painel de configurações à sua direita.`
      });
    }
  } catch (error: any) {
    console.error("Erro geral no endpoint de chat:", error);
    res.status(500).json({
      success: false,
      error: error.message || "Erro desconhecido ao processar a requisição."
    });
  }
});

// Endpoint to export the current project workspace as a ZIP file (excluding node_modules, dist, etc.)
app.get("/api/export-project", async (req, res) => {
  try {
    const zip = new JSZip();
    const rootPath = process.cwd();

    function addFilesToZip(dirPath: string, zipFolder: JSZip) {
      const items = fs.readdirSync(dirPath);
      for (const item of items) {
        const fullPath = path.join(dirPath, item);
        const stat = fs.statSync(fullPath);

        // Exclude large binary modules and build directories
        if (
          item === "node_modules" ||
          item === "dist" ||
          item === ".git" ||
          item === "temp" ||
          item === ".next" ||
          item === "build" ||
          item === "coverage" ||
          item === ".cache"
        ) {
          continue;
        }

        if (stat.isDirectory()) {
          const newFolder = zipFolder.folder(item);
          if (newFolder) {
            addFilesToZip(fullPath, newFolder);
          }
        } else {
          const content = fs.readFileSync(fullPath);
          zipFolder.file(item, content);
        }
      }
    }

    addFilesToZip(rootPath, zip);

    const zipBuffer = await zip.generateAsync({ type: "nodebuffer" });

    res.setHeader("Content-Disposition", "attachment; filename=projeto_completo.zip");
    res.setHeader("Content-Type", "application/zip");
    res.send(zipBuffer);
  } catch (error: any) {
    console.error("Erro ao gerar ZIP do projeto:", error);
    res.status(500).json({ success: false, error: error.message });
  }
});

// Start server and handle Vite middleware
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Servidor rodando na porta ${PORT}`);
  });
}

startServer();
