import React from "react";
import { Download, Check, X, FileDown, ExternalLink, ShieldCheck, AlertCircle, HelpCircle, FileCheck } from "lucide-react";
import { DependencyDownload } from "../types";

interface DownloadCenterProps {
  downloads: DependencyDownload[];
  onApprove: (id: string) => void;
  onRefuse: (id: string) => void;
}

export default function DownloadCenter({ downloads, onApprove, onRefuse }: DownloadCenterProps) {
  const triggerFileDownload = (download: DependencyDownload) => {
    if (download.autoGeneratedContent) {
      // Direct file generation & download for scripts, code, text, json stubs
      const blob = new Blob([download.autoGeneratedContent], { type: "application/octet-stream" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = download.dependencyName;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    } else if (download.recommendedSource) {
      // Opening the official download source
      window.open(download.recommendedSource, "_blank");
    }
  };

  const handleApprove = (id: string, download: DependencyDownload) => {
    onApprove(id);
    // Automatically trigger the download when approved
    triggerFileDownload(download);
  };

  const pendingDownloads = downloads.filter(d => d.status === "pending");
  const completedDownloads = downloads.filter(d => d.status === "approved" || d.status === "downloaded");

  return (
    <div id="download-center-container" className="bg-slate-900 border border-slate-800 text-white rounded-xl overflow-hidden shadow-lg transition-all duration-300">
      <div className="bg-slate-950 border-b border-slate-800 px-4 py-3 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Download className="w-5 h-5 text-emerald-400 animate-pulse" />
          <h3 className="font-semibold text-sm">Central de Downloads e Correções</h3>
        </div>
        <span className="bg-slate-800 text-slate-300 text-[11px] font-bold px-2 py-0.5 rounded-full">
          {downloads.length} {downloads.length === 1 ? "Item" : "Itens"}
        </span>
      </div>

      <div className="p-4">
        {downloads.length === 0 ? (
          <div className="text-center py-6 text-slate-500">
            <HelpCircle className="w-8 h-8 mx-auto mb-2 opacity-50" />
            <p className="text-xs">Nenhum download ou correção pendente.</p>
            <p className="text-[10px] text-slate-600 mt-1">
              Seu projeto está seguro. Se a IA notar erros de DLLs, scripts ou códigos ausentes, ela solicitará permissão para baixá-los ou criá-los aqui!
            </p>
          </div>
        ) : (
          <div className="space-y-4">
            {/* Pending Requests */}
            {pendingDownloads.length > 0 && (
              <div className="space-y-3">
                <h4 className="text-xs font-bold text-emerald-400 uppercase tracking-wider flex items-center gap-1">
                  <AlertCircle className="w-3.5 h-3.5" />
                  Solicitações de Permissão
                </h4>
                {pendingDownloads.map(d => (
                  <div key={d.id} className="bg-slate-950 border-l-4 border-emerald-500 rounded-r-lg p-3 space-y-2 border border-slate-800 transition-all hover:border-slate-700">
                    <div className="flex items-start justify-between gap-2">
                      <div>
                        <span className="text-xs font-mono font-bold bg-slate-800 text-slate-200 px-2 py-0.5 rounded mr-2">
                          {d.fileType.toUpperCase()}
                        </span>
                        <span className="text-xs font-bold text-white break-all">{d.dependencyName}</span>
                      </div>
                      <span className="text-[10px] text-slate-500">{d.timestamp}</span>
                    </div>

                    <p className="text-xs text-slate-300 leading-relaxed bg-slate-900/50 p-2 rounded border border-slate-800/60">
                      {d.reason}
                    </p>

                    {d.recommendedSource && (
                      <div className="text-[10px] text-slate-400 truncate flex items-center gap-1 bg-slate-900 p-1.5 rounded">
                        <ExternalLink className="w-3 h-3 text-indigo-400" />
                        <span className="font-semibold text-slate-300">Origem oficial recomendada:</span>
                        <span className="underline truncate shrink" title={d.recommendedSource}>{d.recommendedSource}</span>
                      </div>
                    )}

                    {d.autoGeneratedContent && (
                      <div className="text-[10px] text-emerald-400 font-medium flex items-center gap-1">
                        <ShieldCheck className="w-3.5 h-3.5" />
                        A IA gerou o código/stub completo para criar este arquivo automaticamente!
                      </div>
                    )}

                    <div className="flex items-center gap-2 pt-1 justify-end">
                      <button
                        onClick={() => onRefuse(d.id)}
                        className="text-xs bg-slate-800 hover:bg-slate-700 text-rose-400 font-medium px-3 py-1.5 rounded-md flex items-center gap-1 transition-colors"
                      >
                        <X className="w-3.5 h-3.5" />
                        Recusar
                      </button>
                      <button
                        onClick={() => handleApprove(d.id, d)}
                        className="text-xs bg-emerald-600 hover:bg-emerald-500 text-white font-bold px-4 py-1.5 rounded-md flex items-center gap-1.5 shadow-md shadow-emerald-900/20 hover:scale-[1.02] active:scale-95 transition-all"
                      >
                        <Check className="w-4 h-4" />
                        Permitir e Corrigir
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            )}

            {/* Approved and Completed Downloads */}
            {completedDownloads.length > 0 && (
              <div className="space-y-2 border-t border-slate-800 pt-3">
                <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider flex items-center gap-1">
                  <FileCheck className="w-3.5 h-3.5" />
                  Histórico de Arquivos Corrigidos
                </h4>
                <div className="space-y-1.5 max-h-40 overflow-y-auto">
                  {completedDownloads.map(d => (
                    <div key={d.id} className="bg-slate-950/80 border border-slate-800/80 rounded p-2 flex items-center justify-between gap-3 text-xs">
                      <div className="truncate flex items-center gap-2">
                        <ShieldCheck className="w-4 h-4 text-emerald-500 shrink-0" />
                        <div className="truncate">
                          <p className="font-mono font-bold text-slate-200 truncate">{d.dependencyName}</p>
                          <p className="text-[10px] text-slate-500 truncate">Autorizado • {d.timestamp}</p>
                        </div>
                      </div>
                      
                      <button
                        onClick={() => triggerFileDownload(d)}
                        className="shrink-0 bg-slate-800 hover:bg-slate-700 hover:text-emerald-400 text-slate-300 p-1.5 rounded transition-colors"
                        title="Baixar novamente"
                      >
                        <FileDown className="w-4 h-4" />
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
