export interface GroundingCitation {
  title: string;
  uri: string;
}

export interface DependencyDownload {
  id: string;
  dependencyName: string;
  reason: string;
  fileType: string;
  recommendedSource?: string;
  autoGeneratedContent?: string;
  status: "pending" | "approved" | "downloaded" | "refused";
  timestamp: string;
}

export interface ZipFileItem {
  name: string;
  size: number;
  content?: string;
  binary?: boolean;
  selected: boolean;
}

export interface ChatPart {
  text?: string;
  inlineData?: {
    mimeType: string;
    data: string; // base64
  };
}

export interface Message {
  id: string;
  role: "user" | "model";
  parts: ChatPart[];
  searchCitations?: GroundingCitation[];
  isPending?: boolean;
  isError?: boolean;
  timestamp: string;
  suggestedDownload?: DependencyDownload;
}

export type GameEngine = "Unity" | "Unreal" | "Godot" | "C++ / SDL / Raylib" | "HTML5 / JS / Phaser" | "Generic";
